routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();
Route::prefix('/')->name('admin.')->namespace('Admin')->group(function(){
  Route::namespace('Auth')->group(function(){
    Route::get('/login', 'LoginController@showLoginView')->name('login');
    Route::post('/login', 'LoginController@Login')->name('login.submit');
    Route::get('/logout', 'LoginController@logout')->name('logout');
  });
  Route::get('/home', 'adminController@index');
  Route::get('/', 'adminController@index')->name('home');
  Route::resource('/permissions', 'permissionsController');
  Route::resource('/users', 'usersController');
  Route::resource('/roles', 'rolesController');

  Route::resource('/puestos', 'puestosController');
  Route::put('/puestos/update/{id}', 'puestosController@update');
  Route::delete('/puestos/destroy/{id}', 'puestosController@destroy');

  Route::resource('/categories', 'categoriesController');
  Route::post('/storeSubCategory/{id}', 'categoriesController@storeSubCategory');
  Route::put('/updateSubCategory/{id}', 'categoriesController@updateSubCategory');
  Route::delete('/categories/deleteSubCategory/{id}', 'categoriesController@deleteSubCategory');

  Route::resource('/colors', 'colorsController');
  Route::resource('/sizes', 'sizesController');
  Route::resource('/warehouse', 'warehouseController');
  Route::get('/wareproducts', 'warehouseController@products')->name("filterproducts");
  Route::resource('/products', 'productsController');
  Route::delete('/products/deleteFiles/{id}/{idPr}', 'productsController@delFile')->name("deleteFiles");
  Route::resource('/prodaddtoware', 'productsWarehouseController');

  Route::resource('/providers', 'providersController');
  Route::resource('/solicitudes', 'solicitudesController');

  Route::resource('/colaboradores', 'colaboradoresController');
  Route::get('/editar_colaboradores/{id?}', 'colaboradoresController@show')->name('editar_colaboradores');
  Route::post('/asignar_colaboradores', 'colaboradoresController@multipleAssign')->name('asignar_colaboradores');

  Route::get('/colaboradores/company/{id}', 'colaboradoresCompanyController@index')->name('colaboradoresCompany');
  Route::post('/colaboradores/company', 'colaboradoresCompanyController@assign')->name('colaboradoresCompanyAssign');
  Route::get('/colaboradores/company/{cid}/{id}', 'colaboradoresCompanyController@unassign')->name('colaboradoresCompanyUnAssign');

  Route::post('/modifyWork/{id}/{idComp}/{nWk?}/{nYr?}', 'colaboradoresCompanyController@updateWorkDone')->name('workModify');

  Route::get('/colaboradores/client/{com_id}/{cli_id}/{assoc_id}', 'colaboradoresClientController@index')->name('colaboradoresClient');
  Route::post('/colaboradores/client/{com_id}/{cli_id}/{assoc_id}', 'colaboradoresClientController@assign')->name('colaboradoresClientAssign');
  Route::get('/colaboradores/client//{com_id}/{cli_id}/{id}', 'colaboradoresClientController@unassign')->name('colaboradoresClientUnAssign');

  Route::resource('/listpetitions', 'petitionslistsController');

  Route::resource('/documentos', 'documentosController');
  Route::get('/documentos_download', 'documentosController@download')->name('documentos_download');

  Route::resource('/company', 'companies\companyController');
  Route::resource('/clients', 'companies\clientsController');
  Route::resource('/clientscompany', 'companies\companyclientsController');
  Route::resource('/clientsjobs', 'companies\clientsJobsController');
  Route::resource('/clientsjobstask', 'companies\clientsJobsTasksController');

  Route::resource('/clientsbranch', 'companies\clientsBranchOfficeController');
  Route::delete('/clientsbranch/{idCli}/{id}', 'companies\clientsBranchOfficeController@destroy');

  Route::resource('/clientsbrancharea', 'companies\clientsBranchAreaController');
  Route::delete('/clientsbrancharea/{idc}/{id}', 'companies\clientsBranchAreaController@destroy');

  Route::resource('/workdone', 'companies\workinghoursController');

  Route::get('/colaboradores/companyReports/{id}/{idComp}/{nWk?}/{nYr?}', 'companies\workinghoursController@workReport')->name('colabCompanyWork');
  Route::post('/colaboradores/companyReports/{id}/{idComp}/{nWk?}/{nYr?}', 'companies\workinghoursController@workReportSave')->name('colabCompanyWorkSave');
  Route::post('/colaboradores/saveVacations/{id}/{idComp}/{nWk?}/{nYr?}', 'companies\workinghoursController@vacationSave')->name('saveVacations');
  Route::post('/colaboradores/savePermission/{id}/{idComp}/{nWk?}/{nYr?}', 'companies\workinghoursController@permissionsSave')->name('savePermission');
  // Route::resource('/shedulesreports', 'companies\shedulesCompanyController');



  Route::resource('/bancos', 'BancosController');
  Route::resource('/contratos', 'ContratosController');

  Route::resource('/archivos', 'archivosController');
  Route::post('/archivos/{id}', 'archivosController@store');
  Route::put('/archivos/{id_file_manager}/{id_file}', 'archivosController@update');
  Route::delete('/archivos/{id_file_manager}/{id_file}', 'archivosController@destroy');

  Route::resource('/tasks', 'tasksController');
  Route::post('/tasks/{id}', 'tasksController@store');
  Route::put('/tasks/{id_task_manager}/{id_task}', 'tasksController@update');
  Route::delete('/tasks/{id_task_manager}/{id_task}', 'tasksController@destroy');

  Route::resource('/horary', 'horaryController');
  Route::post('/horary/{id}', 'horaryController@store');
  Route::put('/horary/{id_task_manager}/{id_task}', 'horaryController@update');
  Route::delete('/horary/{id_task_manager}/{id_task}', 'horaryController@destroy');

  Route::resource('/changeLog', 'changeLogController');
  Route::get('/changeLog/{tipo}/{element_id}', 'changeLogController@show');

  Route::resource('/bodegas', 'bodegasController');
  Route::get('/bodegasCliente/{company_id}', 'bodegasController@showBodegasClientes');
  Route::resource('/bodegasEquipo', 'bodegasEquipoController');

  Route::resource('/egresos', 'egresosController');
  Route::resource('/ingresos', 'ingresosController');

  Route::get('/egresosClientes/{company_id}/{bodega_id}', 'egresosClientesController@index');
  Route::get('/ingresosClientes/{company_id}/{bodega_id}', 'ingresosClientesController@index');

  Route::resource('/egresosEquipo', 'egresosEquipoController');
  Route::resource('/ingresosEquipo', 'ingresosEquipoController');

  Route::resource('/facturas', 'facturasController');
  Route::post('/facturas/{bodega_id}', 'facturasController@store');
  Route::get('/facturasEquipo/{bodega_id}', 'facturasController@showFacturasEquipo');
  Route::post('/facturasEquipo/{bodega_id}', 'facturasController@store');

  Route::get('/productosFactura/{bodega_id}/{factura_id}', 'facturasController@showProductos');
  Route::post('/productosFactura/{bodega_id}/{factura_id}', 'facturasController@storeProductos');
  Route::put('/productosFactura/{bodega_id}/{factura_id}/{ingreso_id}', 'facturasController@updateProductos');
  Route::delete('/productosFactura/{bodega_id}/{factura_id}/destroy/{ingreso_id}', 'facturasController@destroy');

  Route::get('/equiposFactura/{bodega_id}/{factura_id}', 'facturasController@showEquipos');
  Route::post('/equiposFactura/{bodega_id}/{factura_id}', 'facturasController@storeEquipos');
  Route::put('/equiposFactura/{bodega_id}/{factura_id}/{ingreso_id}', 'facturasController@updateEquipos');

  Route::resource('/productos', 'productosController');
  Route::resource('/equipos', 'equiposController');

  Route::resource('/stockEmpresas', 'stockEmpresasController');
  Route::get('/stockEmpresas/{company_id}/{bodega_id}', 'stockEmpresasController@show');
  Route::put('/stockEmpresas/{company_id}/{bodega_id}/{producto_id}', 'stockEmpresasController@egreso');

  Route::resource('/stockEmpresasEquipo', 'stockEmpresasEquipoController');
  Route::put('/stockEmpresasEquipo/{bodega_id}/{equipo_id}', 'stockEmpresasEquipoController@egreso');
  Route::put('/stockEmpresasEquipoIngreso/{bodega_id}/{equipo_id}', 'stockEmpresasEquipoController@ingreso');
  Route::put('/stockEmpresasEquipoBaja/{bodega_id}/{equipo_id}', 'stockEmpresasEquipoController@baja');

  Route::resource('/stockClientes', 'stockClientesController');
  Route::get('/stockClientes/{company_id}/{bodega_id}', 'stockClientesController@show');
  Route::put('/stockClientes/{company_id}/{bodega_id}/{producto_id}', 'stockClientesController@egreso');

  Route::resource('/unidades', 'unidadesController');
  Route::resource('/conversiones', 'conversionesController');
  Route::get('/inboxpetitions/{comany?}/{inbox?}/{type?}/{id?}', 'petitionsinboxController@index')->name("inboxpetitions.index");
  Route::post('/inboxpetitions/{comany?}/{inbox?}/{type?}/{id?}', 'petitionsinboxController@store')->name("inboxpetitions.store");


  Route::get('/cumples', 'cumplesController@index')->name('cumples.index');
  Route::post('/cumples_update', 'cumplesController@update');
  Route::resource('/reportsColabs', 'stockEmpresasController');

  Route::any('/planillas', 'accounting\payrollController@index')->name("planillas.index");
  Route::get('/planillas/{id?}/{month?}', 'accounting\payrollController@show')->name("planillas.show");

  // Route::get('/planillascolabs/{id}/{idComp}/{month?}/{nYr?}', 'accounting\payrollController@payrollinfo')->name("planillascolabs");
  Route::get('/planillascolabs', 'accounting\payrollController@payrollinfo')->name("planillascolabs");

  Route::post('/planillasaprovar', 'accounting\payrollController@aprovationPayroll')->name("aproveplanilla");

app/Http/Controllers/Admin/companies/clientsBranchAreaController.php
<?php

namespace App\Http\Controllers\Admin\companies;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\adminModels\puestosModel;
use App\adminModels\companyclientsBranchAreaModel;
use App\adminModels\companyclientsModel;
use App\adminModels\companyclientsBranchModel;

class clientsBranchAreaController extends Controller
{
    private $baseModel;
    public function __construct()
    {
      $this->middleware('auth:admin');
      $this->baseModel=new companyclientsBranchAreaModel;
    }
    public function show($id)
    {

      $databra = companyclientsBranchModel::find($id);
      $datacli = companyclientsModel::find($databra->idClient);

      $dataRes=$this->baseModel::where("idBranch",$id)->orderBy("created_at")->get();
      return view('admin.companies.showClientBranchesAreas',
            ['menubar'=> $this->list_sidebar(),
             'data'=>$dataRes,
             'idm'=>$id,
             'clientName' => $datacli->clientName,
             'branchName' => $databra->namebranch,
             'clientId' => $datacli->id
           ]);
    }

    public function store(Request $request)
    {
      // dd($request);
      $data = $request->only($this->baseModel->getFillable());
      $this->baseModel->fill($data)->save();
      return redirect()->back()->with('success','Guardado correctamente!');
    }
    public function update(Request $request, $id)
    {
      $finded = $this->baseModel::find($id);
      $data = $request->only($finded->getFillable());
      $finded->fill($data)->save();
      return redirect()->back()->with('info','Actualizado correctamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($idc, $id)
    {
      try {
          $this->baseModel::destroy($id);
          return redirect()->back()->with('warning','Borrado correctamente');
      }catch (\Exception $e) {
         return redirect()->back()->with('error','No se puede eliminar porque hay datos enlazados.'.$e->getCode());
      }
    }



    public static function get_areas(Request $request)
    {

        $id_sucursal = $request->id_sucursal;

        $areas = companyclientsBranchAreaModel::where("idBranch", $id_sucursal)->orderBy("name")->get();

        if (count($areas)>0) {

            $html_options = '<option value="" selected>-- todas --</option>';

            foreach ($areas as $area) {
                if ($request->id_area==$area->id) {
                    $selected = 'selected';
                } else {
                    $selected = '';
                }

                $html_options .= '<option value="'.$area->id.'" '.$selected.'>'.$area->name.'</option>';
            }

        } else {
           $html_options = '';
        }

        return $html_options;
    }



}

app/Http/Controllers/Admin/companies/clientsBranchOfficeController.php
<?php

namespace App\Http\Controllers\Admin\companies;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\adminModels\puestosModel;
use App\adminModels\companyclientsBranchModel;
use App\adminModels\companyclientsModel;
use App\adminModels\bodegasModel;
class clientsBranchOfficeController extends Controller
{
    private $baseModel;
    public function __construct()
    {
      $this->middleware('auth:admin');
      $this->baseModel=new companyclientsBranchModel;
      $this->routeTo='admin.clientsbranch.show';
    }
    public function show($id)
    {
      $dataRes=$this->baseModel::where("idClient",$id)->orderBy("created_at")->get();
      $clientData = companyclientsModel::find($id);

      return view('admin.companies.showClientBranches',
            ['menubar'=> $this->list_sidebar(),
             'data'=>$dataRes,
             'idm'=>$id,
             'clientName' => $clientData->clientName
           ]);
    }

    public function store(Request $request)
    {
      $data = $request->only($this->baseModel->getFillable());

      $bodega = new bodegasModel();
      $bodega_data = [
          'nombre' => $data['namebranch'],
          'tipo' => 'cliente'
      ];
      $bodega->fill($bodega_data)->save();

      $data['bodega_id'] = $bodega->id;


      $this->baseModel->fill($data)->save();
      return redirect()->route($this->routeTo,$request->idClient)->with('success','Guardado correctamente!');
    }
    public function update(Request $request, $id)
    {
      $finded = $this->baseModel::find($id);
      $data = $request->only($finded->getFillable());
      $finded->fill($data)->save();
      return redirect()->route($this->routeTo,$request->idClient)->with('info','Actualizado correctamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($idCli, $id)
    {
      try {
          $this->baseModel::destroy($id);
          return redirect()->back()->with('warning','Borrado correctamente');
      }catch (\Exception $e) {
         return redirect()->back()->with('error','No se puede eliminar porque hay datos enlazados.'.$e->getCode());
      }
    }



    public static function get_sucursales(Request $request)
    {

        $id_cliente = $request->id_cliente;

        $sucursales = companyclientsBranchModel::where("idClient", $id_cliente)->orderBy("namebranch")->get();

        if (count($sucursales)>0) {

            $html_options = '<option value="" selected>-- todas --</option>';

            foreach ($sucursales as $sucursal) {
                if ($request->id_sucursal==$sucursal->id) {
                    $selected = 'selected';
                } else {
                    $selected = '';
                }

                $html_options .= '<option value="'.$sucursal->id.'" '.$selected.'>'.$sucursal->namebranch.'</option>';
            }

        } else {
           $html_options = '';
        }

        return $html_options;
    }



}

app/Http/Controllers/Admin/companies/clientsJobsTasksController.php
<?php

namespace App\Http\Controllers\Admin\companies;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\adminModels\companyclients_jobstodoModel;

class clientsJobsTasksController extends Controller
{
    private $baseModel;
    public function __construct()
    {
      $this->middleware('auth:admin');
      $this->baseModel=new companyclients_jobstodoModel;
      $this->routeTo='admin.clientsjobs.show';
    }


    public function store(Request $request)
    {
      $data = $request->only($this->baseModel->getFillable());
      // unset($data[""]);
      $this->baseModel->fill($data)->save();
      return redirect()->route($this->routeTo,$request->idClients)->with('success','Guardado correctamente!');
    }
    public function update(Request $request, $id)
    {
      $finded = $this->baseModel::find($id);
      $data = $request->only($finded->getFillable());
      unset($data["idJob"]);
      $finded->fill($data)->save();
      return redirect()->route($this->routeTo,$request->idClients)->with('info','Actualizado correctamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      try {
          $this->baseModel::destroy($id);
          return redirect()->back()->with('warning','Borrado correctamente');
      }catch (\Exception $e) {
         return redirect()->back()->with('error','No se puede eliminar porque hay datos enlazados.'.$e->getCode());
      }
    }
}

resources/views/admin/companies/showClientBranches.blade.php
@extends('admin.layouts.master')
@section('main-content')
<script type="text/javascript">
var kad={0:{type:"hddn",nm:"_token",vl:'{{ csrf_token() }}'},
         1:{type:"txt",tl:"Nombre de sede",nm:"namebranch",elv:"0"},
         2:{type:"txt",tl:"Direccion",nm:"address",elv:"1"},
         3:{type:"txt",tl:"Latitud",nm:"latitude",elv:"2"},
         4:{type:"txt",tl:"Longitud",nm:"longitude",elv:"3"},
         5:{type:"txt",tl:"Telefono",nm:"phone1",elv:"4"},
         6:{type:"hddn",vl:"{{$idm}}",nm:"idClient"},
       };
    valdis={clase:"red",text:1};

</script>

<div class="breadcrumb">
    <h1 class="mr-2">Clientes</h1>
    <ul>
        <li><a href="{{url("clients")}}">Inicio</a></li>
        <li>Sedes</li>
    </ul>
</div>
<div class="separator-breadcrumb border-top"></div>

   <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
		  <h3>
              Cliente: <b>{{$clientName}}</b>
          </h3>
          <h3 class="card-title">
              <a href="javascript:"class="" onclick="newfloatv2(kad,null,'{{route('admin.clientsbranch.store')}}');">
                  <i class="ion-ios7-plus-outline "></i>
                  &nbsp;&nbsp;Nueva sede
              </a>
          </h3>
		</div>
        <div class="card-body">
          <div class="table-responsive">
            <table id="sedes_table" class="table" cellspacing="0" width="100%" style="width:100%">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Sede</th>
                  <th>Direccion</th>
                  <th>Latitud</th>
                  <th>Longitud</th>
                  <th>Telefono</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                @php $criti = $crite = []; @endphp
                @foreach ($data as $dataRes)
                  <tr>
                      <td>{{ $loop->index + 1 }}</td>

                  <td > {{$dataRes->namebranch}}</td>
                  <td > {{$dataRes->address}}</td>
                  <td > {{$dataRes->latitude}}</td>
                  <td > {{$dataRes->longitude}}</td>
                  <td > {{$dataRes->phone1}}</td>

                  <td class="td-actions text-left table-subtitle">

                    <a href="{{route('admin.clientsbrancharea.show', $dataRes->id)}}"class="" title="Administrar áreas">
                        <i class="text-20" data-feather="layers"></i>
                    </a>

                    <a  href="javascript:"
                        onclick="modifyfloat('{{$dataRes->id}}',kad,criteria,'literalUrl','{{route('admin.clientsbranch.update',$dataRes->id)}}');">
                        <i class="text-20"data-feather="edit-3"></i>
                    </a>

                    <a  href="javascript:"
                        onclick="deleteD('{{$dataRes->id}}','{{ csrf_token() }}');">
                        <i class="text-12" data-feather="trash"></i>
                    </a>

                  </td>
                  </tr>
                  @php $criti[$dataRes->id] = [$dataRes->namebranch,
                                               $dataRes->address,
                                               $dataRes->latitude,
                                               $dataRes->longitude,
                                               $dataRes->phone1,]; @endphp
                @endforeach
						    </tbody>
               </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    <script type="text/javascript">
      var criteria = @json($criti);
          criterie = @json($crite);

    </script>

@endsection

@section('bottom-js')
    <script>
        $('#sedes_table').DataTable();
    </script>
@endsection

resources/views/admin/companies/showClientCompany.blade.php
@extends('admin.layouts.master')
@section('main-content')
<script type="text/javascript">
var kad={0:{type:"hddn",nm:"_token",vl:'{{ csrf_token() }}'},
         1:{type:"slct",tl:"Cliente",nm:"idClient",vl:@json($clients),elv:"0"},
         2:{type:"hddn",vl:"{{$idm}}",nm:"idCompany"},
       };
    valdis={clase:"red",text:1};

</script>

<div class="breadcrumb">
    <h1 class="mr-2">Empresas</h1>
    <ul>
        <li><a href="{{url('/company')}}">Inicio</a></li>
        <li>Clientes</li>
    </ul>
</div>
<div class="separator-breadcrumb border-top"></div>

<div class="row">
    <div class="col-md-12 mb-2">
        <h1>{{$nameCompany}}</h1>
    </div>
</div>

   <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
					<h3 class="card-title">
              <a class="btn btn-outline-danger btn-icon m-1"
                      href="{{route('admin.company.index')}}">
                 <i class="text-20 i-Back1"></i> </a>
              <a class="btn btn-outline-info m-1"
                  onclick="newfloatv2(kad,null,'{{route('admin.clientscompany.store')}}');">
                <i class="ion-ios7-plus-outline "></i>
                &nbsp;&nbsp;Agregar cliente
              </a>
          </h3>
				</div>
        <div class="card-body">
          <div class="table-responsive">
            <table id="asignar_clientes_table" class="display table table-striped table-bordered">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Cliente</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                @php $criti = $crite = []; @endphp
                @foreach ($data as $dataRes)
                  <tr>
                      <td>{{ $loop->index + 1 }}</td>

                  <td > {{$dataRes->getClient()->first()->clientName}}</td>
                  <td class="td-actions text-left table-subtitle">
                    <a  href="{{ route('admin.colaboradoresClient', ['com_id' => $idm, 'cli_id' => $dataRes->idClient, 'assoc_id'=>$dataRes->id]) }}"
                        title="Colaboradores">
                        <i class="text-20 i-Business-Mens"></i>
                    </a>
                    <a  href="javascript:"
                        onclick="deleteD('{{$dataRes->id}}','{{ csrf_token() }}','{{route('admin.clientscompany.destroy',$dataRes->id)}}');"
                        title="Borrar">
                        <i class="text-12" data-feather="trash"></i>
                    </a>

                  </td>
                  </tr>
                @endforeach
						    </tbody>
               </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    <script type="text/javascript">
      var criteria = @json($criti);
          criterie = @json($crite);

    </script>

@endsection

@section('bottom-js')
    <script>
        $('#asignar_clientes_table').DataTable();
    </script>
@endsection

resources/views/admin/companies/showClientJobs.blade.php
@extends('admin.layouts.master')
@section('main-content')
<script type="text/javascript">
var kad={0:{type:"hddn",nm:"_token",vl:'{{ csrf_token() }}'},
         1:{type:"slct",tl:"Puesto",nm:"idJobCatalog",vl:@json($jobsCatalog),elv:"0"},

         10:{type:"hddn",vl:"{{$idm}}",nm:"idClient"},
       },
       ked={0:{type:"hddn",nm:"_token",vl:'{{ csrf_token() }}'},
                1:{type:"txt",tl:"Nombre de tarea",nm:"title",elv:"0"},
                2:{type:"hddn",vl:"",nm:"idJob",id:"idJob"},
                3:{type:"hddn",vl:"{{$idm}}",nm:"idClients"},
               };
    valdis={clase:"red",text:1};

</script>
   <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
					<h3 class="card-title">
            <a href="javascript:"class="" onclick="newfloatv2(kad,null,'{{route('admin.clientsjobs.store')}}');">
            <i class="ion-ios7-plus-outline "></i>
            &nbsp;&nbsp;Nuevo puesto
          </a>
          </h3>
					<div class="card-options">
						<a href="#" class="card-options-collapse" data-toggle="card-collapse">
              <i class="fe fe-chevron-up"></i>
            </a>
						<a href="#" class="card-options-fullscreen" data-toggle="card-fullscreen">
              <i class="fe fe-maximize"></i>
            </a>
						<a href="#" class="card-options-remove" data-toggle="card-remove">
              <i class="fe fe-x"></i>
            </a>
					</div>
				</div>
        <div class="card-body">
          <div class="table-responsive">
            <table i class="table" cellspacing="0" width="100%" style="width:100%">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Puesto</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                @php $criti = $crite = []; @endphp
                @foreach ($data as $dataRes)
                  <tr>
                      <td>{{ $loop->index + 1 }}</td>

                  <td > {{$dataRes->getJobName()->first()->nombre}}</td>

                  <td class="td-actions text-left table-subtitle">
                    <a  href="javascript:"
                      onclick="newfloatv2(ked,null,'{{route('admin.clientsjobstask.store')}}');$('#idJob').val('{{$dataRes->id}}');">
                        <i class="fa fa-plus "></i>
                    </a>
                    <a  href="javascript:"
                        onclick="modifyfloat('{{$dataRes->id}}',kad,criteria,'literalUrl','{{route('admin.clientsjobs.update',$dataRes->id)}}');">
                        <i class="pe-7s-note "></i>
                    </a>
                    <a  href="javascript:"
                        onclick="deleteD('{{$dataRes->id}}','{{ csrf_token() }}');">
                        <i class="text-12" data-feather="trash-2"></i>
                    </a>

                  </td>
                  </tr>
                  @php $tareas = $dataRes->getTasks()->get();@endphp
                  @if(!empty( $tareas))
                    @foreach( $tareas AS $valus)
                      <tr class="subparone l{{$dataRes->id}}k table-subtitle" style="background-color:#eff7ff;">
                        <td>{{ $loop->index + 1 }}</td>
                        <td >&#8627;{{$valus->title}}</td>
                        <td class="td-actions text-left table-subtitle">
                          <a  href="javascript:"
                              onclick="modifyfloat('{{$valus->id}}',ked,criterie,'literalUrl','{{route('admin.clientsjobstask.update',$valus->id)}}');">
                              <i class="pe-7s-note "></i>
                          </a>
                          <a  href="javascript:"
                              onclick="deleteD('{{$valus->id}}','{{ csrf_token() }}');">
                              <i class="pe-7s-trash "></i>
                          </a>
                        </td>
                      </tr>
                      @php $crite[$valus->id]=[$valus->title,$valus->id]; @endphp
                    @endforeach
                  @endif
                  @php $criti[$dataRes->id] = [$dataRes->idJobCatalog]; @endphp
                @endforeach
						    </tbody>
               </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    <script type="text/javascript">
      var criteria = @json($criti);
          criterie = @json($crite);

    </script>

@endsection