routes/web.php
  Route::namespace('Auth')->group(function(){
    Route::get('/login', 'LoginController@showLoginView')->name('login');
    Route::post('/login', 'LoginController@Login')->name('login.submit');
    Route::get('/logout', 'LoginController@logout')->name('logout');
  });
  Route::get('/home', 'adminController@index');
  Route::get('/', 'adminController@index')->name('home');
  Route::resource('/permissions', 'permissionsController');
  Route::resource('/users', 'usersController');
  Route::resource('/roles', 'rolesController');

  Route::resource('/puestos', 'puestosController');
  Route::put('/puestos/update/{id}', 'puestosController@update');
  Route::delete('/puestos/destroy/{id}', 'puestosController@destroy');

  Route::resource('/categories', 'categoriesController');
  Route::post('/storeSubCategory/{id}', 'categoriesController@storeSubCategory');
  Route::put('/updateSubCategory/{id}', 'categoriesController@updateSubCategory');
  Route::delete('/categories/deleteSubCategory/{id}', 'categoriesController@deleteSubCategory');

  Route::resource('/colors', 'colorsController');
  Route::resource('/sizes', 'sizesController');
  Route::resource('/warehouse', 'warehouseController');
  Route::get('/wareproducts', 'warehouseController@products')->name("filterproducts");
  Route::resource('/products', 'productsController');
  Route::delete('/products/deleteFiles/{id}/{idPr}', 'productsController@delFile')->name("deleteFiles");
  Route::resource('/prodaddtoware', 'productsWarehouseController');

  Route::resource('/providers', 'providersController');
  Route::resource('/solicitudes', 'solicitudesController');

  Route::resource('/colaboradores', 'colaboradoresController');
  Route::get('/editar_colaboradores/{id?}', 'colaboradoresController@show')->name('editar_colaboradores');
  Route::post('/asignar_colaboradores', 'colaboradoresController@multipleAssign')->name('asignar_colaboradores');

  Route::get('/colaboradores/company/{id}', 'colaboradoresCompanyController@index')->name('colaboradoresCompany');
  Route::post('/colaboradores/company', 'colaboradoresCompanyController@assign')->name('colaboradoresCompanyAssign');
  Route::get('/colaboradores/company/{cid}/{id}', 'colaboradoresCompanyController@unassign')->name('colaboradoresCompanyUnAssign');

  Route::post('/modifyWork/{id}/{idComp}/{nWk?}/{nYr?}', 'colaboradoresCompanyController@updateWorkDone')->name('workModify');

  Route::get('/colaboradores/client/{com_id}/{cli_id}/{assoc_id}', 'colaboradoresClientController@index')->name('colaboradoresClient');
  Route::post('/colaboradores/client/{com_id}/{cli_id}/{assoc_id}', 'colaboradoresClientController@assign')->name('colaboradoresClientAssign');
  Route::get('/colaboradores/client//{com_id}/{cli_id}/{id}', 'colaboradoresClientController@unassign')->name('colaboradoresClientUnAssign');

  Route::resource('/listpetitions', 'petitionslistsController');

  Route::resource('/documentos', 'documentosController');
  Route::get('/documentos_download', 'documentosController@download')->name('documentos_download');

  Route::resource('/company', 'companies\companyController');
  Route::resource('/clients', 'companies\clientsController');
  Route::resource('/clientscompany', 'companies\companyclientsController');
  Route::resource('/clientsjobs', 'companies\clientsJobsController');
  Route::resource('/clientsjobstask', 'companies\clientsJobsTasksController');

  Route::resource('/clientsbranch', 'companies\clientsBranchOfficeController');
  Route::delete('/clientsbranch/{idCli}/{id}', 'companies\clientsBranchOfficeController@destroy');

  Route::resource('/clientsbrancharea', 'companies\clientsBranchAreaController');
  Route::delete('/clientsbrancharea/{idc}/{id}', 'companies\clientsBranchAreaController@destroy');

  Route::resource('/workdone', 'companies\workinghoursController');

  Route::get('/colaboradores/companyReports/{id}/{idComp}/{nWk?}/{nYr?}', 'companies\workinghoursController@workReport')->name('colabCompanyWork');
  Route::post('/colaboradores/companyReports/{id}/{idComp}/{nWk?}/{nYr?}', 'companies\workinghoursController@workReportSave')->name('colabCompanyWorkSave');
  Route::post('/colaboradores/saveVacations/{id}/{idComp}/{nWk?}/{nYr?}', 'companies\workinghoursController@vacationSave')->name('saveVacations');
  Route::post('/colaboradores/savePermission/{id}/{idComp}/{nWk?}/{nYr?}', 'companies\workinghoursController@permissionsSave')->name('savePermission');
  // Route::resource('/shedulesreports', 'companies\shedulesCompanyController');



  Route::resource('/bancos', 'BancosController');
  Route::resource('/contratos', 'ContratosController');

  Route::resource('/archivos', 'archivosController');
  Route::post('/archivos/{id}', 'archivosController@store');
  Route::put('/archivos/{id_file_manager}/{id_file}', 'archivosController@update');
  Route::delete('/archivos/{id_file_manager}/{id_file}', 'archivosController@destroy');

  Route::resource('/tasks', 'tasksController');
  Route::post('/tasks/{id}', 'tasksController@store');
  Route::put('/tasks/{id_task_manager}/{id_task}', 'tasksController@update');
  Route::delete('/tasks/{id_task_manager}/{id_task}', 'tasksController@destroy');

  Route::resource('/horary', 'horaryController');
  Route::post('/horary/{id}', 'horaryController@store');
  Route::put('/horary/{id_task_manager}/{id_task}', 'horaryController@update');
  Route::delete('/horary/{id_task_manager}/{id_task}', 'horaryController@destroy');

  Route::resource('/changeLog', 'changeLogController');
  Route::get('/changeLog/{tipo}/{element_id}', 'changeLogController@show');

  Route::resource('/bodegas', 'bodegasController');
  Route::get('/bodegasCliente/{company_id}', 'bodegasController@showBodegasClientes');
  Route::resource('/bodegasEquipo', 'bodegasEquipoController');

  Route::resource('/egresos', 'egresosController');
  Route::resource('/ingresos', 'ingresosController');

  Route::get('/egresosClientes/{company_id}/{bodega_id}', 'egresosClientesController@index');
  Route::get('/ingresosClientes/{company_id}/{bodega_id}', 'ingresosClientesController@index');

  Route::resource('/egresosEquipo', 'egresosEquipoController');
  Route::resource('/ingresosEquipo', 'ingresosEquipoController');

  Route::resource('/facturas', 'facturasController');
  Route::post('/facturas/{bodega_id}', 'facturasController@store');
  Route::get('/facturasEquipo/{bodega_id}', 'facturasController@showFacturasEquipo');
  Route::post('/facturasEquipo/{bodega_id}', 'facturasController@store');

  Route::get('/productosFactura/{bodega_id}/{factura_id}', 'facturasController@showProductos');
  Route::post('/productosFactura/{bodega_id}/{factura_id}', 'facturasController@storeProductos');
  Route::put('/productosFactura/{bodega_id}/{factura_id}/{ingreso_id}', 'facturasController@updateProductos');
  Route::delete('/productosFactura/{bodega_id}/{factura_id}/destroy/{ingreso_id}', 'facturasController@destroy');

  Route::get('/equiposFactura/{bodega_id}/{factura_id}', 'facturasController@showEquipos');
  Route::post('/equiposFactura/{bodega_id}/{factura_id}', 'facturasController@storeEquipos');
  Route::put('/equiposFactura/{bodega_id}/{factura_id}/{ingreso_id}', 'facturasController@updateEquipos');

  Route::resource('/productos', 'productosController');
  Route::resource('/equipos', 'equiposController');

  Route::resource('/stockEmpresas', 'stockEmpresasController');
  Route::get('/stockEmpresas/{company_id}/{bodega_id}', 'stockEmpresasController@show');
  Route::put('/stockEmpresas/{company_id}/{bodega_id}/{producto_id}', 'stockEmpresasController@egreso');

  Route::resource('/stockEmpresasEquipo', 'stockEmpresasEquipoController');
  Route::put('/stockEmpresasEquipo/{bodega_id}/{equipo_id}', 'stockEmpresasEquipoController@egreso');
  Route::put('/stockEmpresasEquipoIngreso/{bodega_id}/{equipo_id}', 'stockEmpresasEquipoController@ingreso');
  Route::put('/stockEmpresasEquipoBaja/{bodega_id}/{equipo_id}', 'stockEmpresasEquipoController@baja');

  Route::resource('/stockClientes', 'stockClientesController');
  Route::get('/stockClientes/{company_id}/{bodega_id}', 'stockClientesController@show');
  Route::put('/stockClientes/{company_id}/{bodega_id}/{producto_id}', 'stockClientesController@egreso');

  Route::resource('/unidades', 'unidadesController');
  Route::resource('/conversiones', 'conversionesController');
  Route::get('/inboxpetitions/{comany?}/{inbox?}/{type?}/{id?}', 'petitionsinboxController@index')->name("inboxpetitions.index");
  Route::post('/inboxpetitions/{comany?}/{inbox?}/{type?}/{id?}', 'petitionsinboxController@store')->name("inboxpetitions.store");


  Route::get('/cumples', 'cumplesController@index')->name('cumples.index');
  Route::post('/cumples_update', 'cumplesController@update');
  Route::resource('/reportsColabs', 'stockEmpresasController');

  Route::any('/planillas', 'accounting\payrollController@index')->name("planillas.index");
  Route::get('/planillas/{id?}/{month?}', 'accounting\payrollController@show')->name("planillas.show");

  // Route::get('/planillascolabs/{id}/{idComp}/{month?}/{nYr?}', 'accounting\payrollController@payrollinfo')->name("planillascolabs");
  Route::get('/planillascolabs', 'accounting\payrollController@payrollinfo')->name("planillascolabs");

  Route::post('/planillasaprovar', 'accounting\payrollController@aprovationPayroll')->name("aproveplanilla");

  Route::post('/aprobar_planilla', 'accounting\payrollController@aprobar_planilla')->name("aprobar_planilla");
  Route::post('/update_planilla', 'accounting\payrollController@update_planilla')->name("update_planilla");


  // horas extras
  Route::any('/horas', 'accounting\horasController@index')->name("horas.index");
  Route::get('/horas_colab', 'accounting\horasController@horas_colab')->name("horas_colab");
  Route::post('/aprobar_colab_horas', 'accounting\horasController@aprobar_colab')->name("aprobar_colab");
  Route::post('/aprobar_horas', 'accounting\horasController@aprobar_horas')->name("aprobar_horas");

app/Http/Controllers/Admin/tasksController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\adminModels\tasksModel;
use Illuminate\Support\Facades\Storage;

class tasksController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function show($id){

      $reference = explode('_', $id);
      $name = $reference[0];
      $breadcrumb = session('breadcrumb') != null ? session('breadcrumb') : [];

      $files = tasksModel::where('id_task_manager', $id)->get();

      foreach($files as $tl){
          $tl['file'] = Storage::url($tl->url);
      }

      return view('admin.tasks.show',
            [
                'menubar'=> $this->list_sidebar(),
                'files'=>$files,
                'id_file_manager' => $id,
                'breadcrumb' => $breadcrumb,
                'name' => $name
            ]);
    }

    public function store(Request $request, $id) {

      $archivos = new tasksModel;
      $data = $request->only($archivos->getFillable());

      $data['id_task_manager'] = $id;

      $archivos->fill($data)->save();
      return redirect()->back()->with('success','Guardado correctamente!');
    }

    public function update(Request $request, $id_file_manager, $id) {
      $archivos = new tasksModel;
      $elm = $archivos::find($id);
      $data = $request->only($archivos->getFillable());

      $elm->fill($data)->save();

      return redirect()->back()->with('info','Actualizado correctamente!');
    }

    public function destroy($id_file_manager, $id_file) {

      $elm = tasksModel::find($id_file);

      Storage::disk('public')->delete($elm->url);

      $elm->delete($id_file);

      return redirect()->back()->with('warning','Borrado correctamente!');
    }

}

resources/views/admin/tasks/show.blade.php
@extends('admin.layouts.master')
@section('main-content')
<script type="text/javascript">
  var kad={0:{type:"hddn",nm:"_token",vl:'{{ csrf_token() }}'},
          1:{type:"txt",tl:"Nombre",nm:"name",elv:"0",nxt:6},
          2:{type:"txtarea",tl:"Descripción",nm:"description",elv:"1",nxt:12},
          3:{type:"nbr",tl:"Cantidad",nm:"count",elv:"2",nxt:12},
      }
  var conform={action:"{{route('admin.permissions.store')}}"}
    valdis={clase:"red",text:1,checkbox:1,radio:1};
</script>
@php
    $criti = [];
@endphp

<div class="breadcrumb">
    <h1 class="mr-2">{{$breadcrumb['base']}}</h1>
    <ul>
        <li> <a href="{{url($breadcrumb['inicio'])}}"> Inicio</a> </li>
        <li>Administrar metas</li>
    </ul>
</div>
<div class="separator-breadcrumb border-top"></div>

   <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
		  <h3 class="card-title">
            Metas de: <b>{{$name}}</b>
          </h3>
          <h5><a href="javascript:"class="" onclick="newfloatv2(kad);"> <i class="ion-ios7-plus-outline "></i>&nbsp;&nbsp;Agregar meta </a></h5>
				</div>

        <div class="card-body">
          <div class="table-responsive">
            <table id="tareas_table" class="display table table-striped table-bordered" cellspacing="0" width="100%" style="width:100%">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Nombre</th>
                      <th>Descripcion</th>
                      <th>Cantidad</th>
                      <th>Opciones</th>
                    </tr>
                  </thead>

                  <tbody>
                    @foreach ($files as $f)
                      <tr>
                        <td>{{ $loop->index + 1 }}</td>
                        <td class="hidden-xs">{{$f->name}}</td>
                        <td class="hidden-xs">{{$f->description}}</td>
                        <td class="hidden-xs">{{$f->count}}</td>

                        <td>

                          <a href="javascript:" class="" onclick="modifyfloat('{{$f->id}}',kad,criteria);" title="Editar archivo">
                              <i class="text-20"data-feather="edit-3"></i>
                          </a>

                          <a href="javascript:"onclick="deleteD('{{$f->id}}','{{ csrf_token() }}');" title="Eliminar archivo">
                              <i class="text-12" data-feather="trash"></i>
                          </a>
                        </td>
                      </tr>
                      @php
                        $criti[$f->id] = [$f->name, $f->description, $f->count];
                      @endphp

                    @endforeach
    		       </tbody>
               </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    <script type="text/javascript">
      var criteria = <?=json_encode($criti)?>;
      function fillimg(sto)
      {
        $("#imag").val(sto);
        flotantecloseblank();
      }
    </script>
    @component('components.messagesForm')
    @endcomponent
@endsection

@section('bottom-js')
    <script>
        $('#tareas_table').DataTable();
    </script>
@endsection